---
title: "CODEBOOK"
output: html_document
---
## DATA
The output tidy_data.txt is based on an experiment where activity data was collected from 30 participants using the accelerometer and gyroscope in the subjects' Samsung Galaxy X Smartphones. The first row is the column names and the subsequent rows are the averages of each variable by subject and activity type. Additional information on the study can be found here:   http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones as well as the README.txt file once the data is unzipped

## Transformations
1. Downloads data from https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip where information on Human Activity Recognition of 30 subjects carrying Samsung Galaxy X Smartphones is stored

2. Unzips the data into a directory specified by the user in setwd()

3. Reads in the data stored in the 2 folders unzipped in the directory: train and test

4. Assigns column names to training and test data and uses the information from the features
file to label the activity type

5. Merges training and test data

6. Extracts only the columns that contain mean and standard deviation

7. Joins the descriptive activity type data to the merged table based on the activity id to create a descriptive activity type column

8. Loops through the column names to replace the variable names with more descriptive ones
using regular expressions in order to make the data more user-friendly

9. A second tidy data set is created that averages each variable by subject and activity type

10. Writes a txt file with the tidy data to the user's directory

## Dataset files
* features_info.txt: Shows information about the variables used
* features.txt: List of all features (variables)
* activity_labels.txt: Links the activity name to class label
* train/X_train.txt: Training set with subject data
* train/y_train.txt: Training labels used to link with activity name 
* test/X_test.txt: Test set with subject data
* test/y_test.txt: Test labels used to link with activity name

## Variables
* Subject: Anonymized subjects in the study, 1-30

* ActivityType: Type of activities performed by the subjects, 6 in total
  1. WALKING: subject walking during test
  2. WALKING_UPSTAIRS: subject walking upstairs during test
  3. WALKING_DOWNSTAIRS: subject walking downstairs during test
  4. SITTTING: subject standing during test
  6. LAYING: subject laying during test

## Measurements
* Signals were used to estimate variables of the feature vector for 3 different pattens denoted by  
  XYZ (signal directions):
    * tBodyAcc-XYZ
    * tGravityAcc-XYZ
    * tBodyAccJerk-XYZ
    * tBodyGyro-XYZ
    * tBodyGyroJerk-XYZ
    * tBodyAccMag
    * tGravityAccMag
    * tBodyAccJerkMag
    * tBodyGyroMag
    * tBodyGyroJerkMag
    * fBodyAcc-XYZ
    * fBodyAccJerk-XYZ
    * fBodyGyro-XYZ
    * fBodyAccMag
    * fBodyAccJerkMag
    * fBodyGyroMag
    * fBodyGyroJerkMag

- Variables were estimated based on the signals and they included: 
    * mean(): Mean value
    * std(): Standard deviation
    * mad(): Median absolute deviation 
    * max(): Largest value in array
    * min(): Smallest value in array
    * sma(): Signal magnitude area
    * energy(): Energy measure. Sum of the squares divided by the number of values. 
    * iqr(): Interquartile range 
    * entropy(): Signal entropy
    * arCoeff(): Autorregresion coefficients with Burg order equal to 4
    * correlation(): correlation coefficient between two signals
    * maxInds(): index of the frequency component with largest magnitude
    * meanFreq(): Weighted average of the frequency components to obtain a mean frequency
    * skewness(): skewness of the frequency domain signal 
    * kurtosis(): kurtosis of the frequency domain signal 
    * bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
    * angle(): Angle between to vectors

* Additional vectors: 
    * gravityMean
    * tBodyAccMean
    * tBodyAccJerkMean
    * tBodyGyroMean
    * tBodyGyroJerkMean
    
