---
title: "README"
output: html_document
---

## Repository:

* README.Rmd: dataset overview and steps taken to transform it
* CODEBOOK.Rmd: content of the data set and how it was transformed
* run_analysis.R: script that generates the tidy data
* tidy_data.txt: tidy data that averages each variable by subject and activity type

## User Information
After checking out run_analysis.R modify line 10 to your working directory and then run the script. It will download the experiment information from http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones, transform it using the steps in CODEBOOK.Rmd, and generate a tidy_data.txt file in the working directory

## Project Summary
Project instructions: 

1. Merges the training and the test sets to create one data set
2. Extracts only the measurements on the mean and standard deviation for each measurement
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject

## Transformations
1. Downloads data from https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip where information on Human Activity Recognition of 30 subjects carrying Samsung Galaxy X Smartphones is stored

2. Unzips the data into a directory specified by the user in setwd()

3. Reads in the data stored in the 2 folders unzipped in the directory: train and test

4. Assigns column names to training and test data and uses the information from the features
file to label the activity type

5. Merges training and test data

6. Extracts only the columns that contain mean and standard deviation

7. Joins the descriptive activity type data to the merged table based on the activity id to create a descriptive activity type column

8. Loops through the column names to replace the variable names with more descriptive ones
using regular expressions in order to make the data more user-friendly

9. A second tidy data set is created that averages each variable by subject and activity type

10. Writes a txt file with the tidy data to the user's directory

